const hsk1_vocabulary = [
    // Đại từ
    { id: 1, hanzi: "我", pinyin: "wǒ", vi: "Tôi", example: "我是学生。 (Tôi là học sinh)", category: "Đại từ" },
    { id: 2, hanzi: "你", pinyin: "nǐ", vi: "Bạn", example: "你好！ (Chào bạn)", category: "Đại từ" },
    { id: 3, hanzi: "他", pinyin: "tā", vi: "Anh ấy", example: "他是老师。 (Anh ấy là giáo viên)", category: "Đại từ" },
    { id: 4, hanzi: "她", pinyin: "tā", vi: "Cô ấy", example: "她是我妈妈。 (Cô ấy là mẹ tôi)", category: "Đại từ" },
    { id: 5, hanzi: "我们", pinyin: "wǒmen", vi: "Chúng tôi", example: "我们去吃饭。 (Chúng ta đi ăn)", category: "Đại từ" },
    { id: 6, hanzi: "这", pinyin: "zhè", vi: "Này, đây", example: "这是什么？ (Đây là cái gì?)", category: "Đại từ" },
    { id: 7, hanzi: "那", pinyin: "nà", vi: "Kia, đó", example: "那个人是谁？ (Người kia là ai?)", category: "Đại từ" },
    { id: 8, hanzi: "哪", pinyin: "nǎ", vi: "Nào", example: "你去哪里？ (Bạn đi đâu?)", category: "Đại từ" },
    { id: 9, hanzi: "谁", pinyin: "shéi", vi: "Ai", example: "他是谁？ (Anh ấy là ai?)", category: "Đại từ" },
    { id: 10, hanzi: "什么", pinyin: "shénme", vi: "Cái gì", example: "你叫什么名字？ (Bạn tên là gì?)", category: "Đại từ" },
    { id: 11, hanzi: "多少", pinyin: "duōshao", vi: "Bao nhiêu", example: "多少钱？ (Bao nhiêu tiền?)", category: "Đại từ" },
    { id: 12, hanzi: "几", pinyin: "jǐ", vi: "Mấy, vài", example: "几点了？ (Mấy giờ rồi?)", category: "Đại từ" },
    { id: 13, hanzi: "怎么", pinyin: "zěnme", vi: "Thế nào, sao", example: "怎么卖？ (Bán thế nào?)", category: "Đại từ" },
    { id: 14, hanzi: "怎么样", pinyin: "zěnmeyàng", vi: "Như thế nào", example: "天气怎么样？ (Thời tiết thế nào?)", category: "Đại từ" },

    // Danh từ
    { id: 15, hanzi: "家", pinyin: "jiā", vi: "Nhà, gia đình", example: "我回我家。 (Tôi về nhà tôi)", category: "Danh từ" },
    { id: 16, hanzi: "学校", pinyin: "xuéxiào", vi: "Trường học", example: "我在学校。 (Tôi ở trường học)", category: "Danh từ" },
    { id: 17, hanzi: "饭店", pinyin: "fàndiàn", vi: "Nhà hàng", example: "去饭店吃饭。 (Đến nhà hàng ăn cơm)", category: "Danh từ" },
    { id: 18, hanzi: "商店", pinyin: "shāngdiàn", vi: "Cửa hàng", example: "去商店买东西。 (Đến cửa hàng mua đồ)", category: "Danh từ" },
    { id: 19, hanzi: "医院", pinyin: "yīyuàn", vi: "Bệnh viện", example: "他在医院工作。 (Anh ấy làm ở bệnh viện)", category: "Danh từ" },
    { id: 20, hanzi: "火车站", pinyin: "huǒchēzhàn", vi: "Ga xe lửa", example: "火车站怎么走？ (Đường đến ga xe lửa đi thế nào?)", category: "Danh từ" },
    { id: 21, hanzi: "中国", pinyin: "Zhōngguó", vi: "Trung Quốc", example: "我是中国人。 (Tôi là người Trung Quốc)", category: "Danh từ" },
    { id: 22, hanzi: "北京", pinyin: "Běijīng", vi: "Bắc Kinh", example: "我去北京。 (Tôi đi Bắc Kinh)", category: "Danh từ" },
    { id: 23, hanzi: "上", pinyin: "shàng", vi: "Trên", example: "桌子上 (Trên bàn)", category: "Danh từ" },
    { id: 24, hanzi: "下", pinyin: "xià", vi: "Dưới", example: "椅子下 (Dưới ghế)", category: "Danh từ" },
    { id: 25, hanzi: "前面", pinyin: "qiánmiàn", vi: "Phía trước", example: "在前面 (Ở phía trước)", category: "Danh từ" },
    { id: 26, hanzi: "后面", pinyin: "hòumiàn", vi: "Phía sau", example: "在后面 (Ở phía sau)", category: "Danh từ" },
    { id: 27, hanzi: "里", pinyin: "lǐ", vi: "Trong", example: "在家里 (Ở trong nhà)", category: "Danh từ" },
    { id: 28, hanzi: "爸爸", pinyin: "bàba", vi: "Bố", example: "我爱爸爸。 (Tôi yêu bố)", category: "Danh từ" },
    { id: 29, hanzi: "妈妈", pinyin: "māma", vi: "Mẹ", example: "我爱妈妈。 (Tôi yêu mẹ)", category: "Danh từ" },
    { id: 30, hanzi: "儿子", pinyin: "érzi", vi: "Con trai", example: "他是我儿子。 (Nó là con trai tôi)", category: "Danh từ" },
    { id: 31, hanzi: "女儿", pinyin: "nǚ'ér", vi: "Con gái", example: "她是我女儿。 (Nó là con gái tôi)", category: "Danh từ" },
    { id: 32, hanzi: "老师", pinyin: "lǎoshī", vi: "Giáo viên", example: "李老师好！ (Chào thầy Lý!)", category: "Danh từ" },
    { id: 33, hanzi: "学生", pinyin: "xuésheng", vi: "Học sinh", example: "我是学生。 (Tôi là học sinh)", category: "Danh từ" },
    { id: 34, hanzi: "同学", pinyin: "tóngxué", vi: "Bạn học", example: "同学们好！ (Chào các em học sinh!)", category: "Danh từ" },
    { id: 35, hanzi: "朋友", pinyin: "péngyou", vi: "Bạn bè", example: "他是我朋友。 (Cậu ấy là bạn tôi)", category: "Danh từ" },
    { id: 36, hanzi: "医生", pinyin: "yīshēng", vi: "Bác sĩ", example: "他是医生。 (Anh ấy là bác sĩ)", category: "Danh từ" },
    { id: 37, hanzi: "先生", pinyin: "xiānsheng", vi: "Ông, ngài", example: "王先生好！ (Chào ông Vương!)", category: "Danh từ" },

    // Động từ
    { id: 38, hanzi: "谢谢", pinyin: "xièxie", vi: "Cảm ơn", example: "谢谢你！ (Cảm ơn bạn!)", category: "Động từ" },
    { id: 39, hanzi: "不客气", pinyin: "búkèqi", vi: "Đừng khách sáo", example: "A: 谢谢 - B: 不客气。 (A: Cảm ơn - B: Đừng khách sáo)", category: "Động từ" },
    { id: 40, hanzi: "再见", pinyin: "zàijiàn", vi: "Tạm biệt", example: "明天再见！ (Ngày mai gặp lại!)", category: "Động từ" },
    { id: 41, hanzi: "请", pinyin: "qǐng", vi: "Xin mời", example: "请坐！ (Mời ngồi!)", category: "Động từ" },
    { id: 42, hanzi: "对不起", pinyin: "duìbuqǐ", vi: "Xin lỗi", example: "对不起！ (Xin lỗi!)", category: "Động từ" },
    { id: 43, hanzi: "没关系", pinyin: "méiguānxi", vi: "Không có gì", example: "没关系！ (Không sao đâu!)", category: "Động từ" },
    { id: 44, hanzi: "是", pinyin: "shì", vi: "Là", example: "我是中国人。 (Tôi là người Trung Quốc)", category: "Động từ" },
    { id: 45, hanzi: "有", pinyin: "yǒu", vi: "Có", example: "我有一个苹果。 (Tôi có một quả táo)", category: "Động từ" },
    { id: 46, hanzi: "看", pinyin: "kàn", vi: "Nhìn, xem", example: "看电视。 (Xem tivi)", category: "Động từ" },
    { id: 47, hanzi: "听", pinyin: "tīng", vi: "Nghe", example: "听音乐。 (Nghe nhạc)", category: "Động từ" },
    { id: 48, hanzi: "说话", pinyin: "shuōhuà", vi: "Nói chuyện", example: "他在说话。 (Anh ấy đang nói chuyện)", category: "Động từ" },
    { id: 49, hanzi: "读", pinyin: "dú", vi: "Đọc", example: "读书。 (Đọc sách)", category: "Động từ" },
    { id: 50, hanzi: "写", pinyin: "xiě", vi: "Viết", example: "写字。 (Viết chữ)", category: "Động từ" },
    { id: 51, hanzi: "看见", pinyin: "kànjiàn", vi: "Nhìn thấy", example: "我看见他了。 (Tôi nhìn thấy anh ấy rồi)", category: "Động từ" },
    { id: 52, hanzi: "叫", pinyin: "jiào", vi: "Gọi, tên là", example: "我叫玛丽。 (Tôi tên là Mary)", category: "Động từ" },
    { id: 53, hanzi: "来", pinyin: "lái", vi: "Đến", example: "他来了。 (Anh ấy đến rồi)", category: "Động từ" },
    { id: 54, hanzi: "回", pinyin: "huí", vi: "Về", example: "回家。 (Về nhà)", category: "Động từ" },
    { id: 55, hanzi: "去", pinyin: "qù", vi: "Đi", example: "去学校。 (Đi đến trường)", category: "Động từ" },
    { id: 56, hanzi: "吃", pinyin: "chī", vi: "Ăn", example: "吃饭。 (Ăn cơm)", category: "Động từ" },
    { id: 57, hanzi: "喝", pinyin: "hē", vi: "Uống", example: "喝水。 (Uống nước)", category: "Động từ" },

    // Tính từ
    { id: 58, hanzi: "好", pinyin: "hǎo", vi: "Tốt, khỏe", example: "很好。 (Rất tốt)", category: "Tính từ" },
    { id: 59, hanzi: "大", pinyin: "dà", vi: "To, lớn", example: "很大。 (Rất to)", category: "Tính từ" },
    { id: 60, hanzi: "小", pinyin: "xiǎo", vi: "Nhỏ, bé", example: "很小。 (Rất nhỏ)", category: "Tính từ" },
    { id: 61, hanzi: "多", pinyin: "duō", vi: "Nhiều", example: "很多人。 (Rất nhiều người)", category: "Tính từ" },
    { id: 62, hanzi: "少", pinyin: "shǎo", vi: "Ít", example: "很少。 (Rất ít)", category: "Tính từ" },
    { id: 63, hanzi: "冷", pinyin: "lěng", vi: "Lạnh", example: "今天很冷。 (Hôm nay rất lạnh)", category: "Tính từ" },
    { id: 64, hanzi: "热", pinyin: "rè", vi: "Nóng", example: "今天很热。 (Hôm nay rất nóng)", category: "Tính từ" },
    { id: 65, hanzi: "高兴", pinyin: "gāoxìng", vi: "Vui vẻ", example: "我很高兴。 (Tôi rất vui)", category: "Tính từ" },

    // Số đếm & Thời gian
    { id: 66, hanzi: "一", pinyin: "yī", vi: "Một", example: "一个 (Một cái)", category: "Số đếm & Thời gian" },
    { id: 67, hanzi: "二", pinyin: "èr", vi: "Hai", example: "二月 (Tháng 2)", category: "Số đếm & Thời gian" },
    { id: 68, hanzi: "三", pinyin: "sān", vi: "Ba", example: "三个 (Ba cái)", category: "Số đếm & Thời gian" },
    { id: 69, hanzi: "今天", pinyin: "jīntiān", vi: "Hôm nay", example: "今天很好。 (Hôm nay rất tốt)", category: "Số đếm & Thời gian" },
    { id: 70, hanzi: "明天", pinyin: "míngtiān", vi: "Ngày mai", example: "明天见。 (Ngày mai gặp)", category: "Số đếm & Thời gian" },
    { id: 71, hanzi: "昨天", pinyin: "zuótiān", vi: "Hôm qua", example: "昨天很冷。 (Hôm qua rất lạnh)", category: "Số đếm & Thời gian" },
    { id: 72, hanzi: "现在", pinyin: "xiànzài", vi: "Bây giờ", example: "现在几点？ (Bây giờ là mấy giờ?)", category: "Số đếm & Thời gian" },
    { id: 73, hanzi: "年", pinyin: "nián", vi: "Năm", example: "2023年 (Năm 2023)", category: "Số đếm & Thời gian" },
    { id: 74, hanzi: "月", pinyin: "yuè", vi: "Tháng", example: "一月 (Tháng 1)", category: "Số đếm & Thời gian" },
    { id: 75, hanzi: "日", pinyin: "rì", vi: "Ngày", example: "三日 (Ngày mùng 3)", category: "Số đếm & Thời gian" },
    
    // Lượng từ & Hư từ
    { id: 76, hanzi: "个", pinyin: "gè", vi: "Cái, quả, người", example: "一个人 (Một người)", category: "Lượng từ & Hư từ" },
    { id: 77, hanzi: "岁", pinyin: "suì", vi: "Tuổi", example: "十岁 (Mười tuổi)", category: "Lượng từ & Hư từ" },
    { id: 78, hanzi: "不", pinyin: "bù", vi: "Không", example: "不是 (Không phải)", category: "Lượng từ & Hư từ" },
    { id: 79, hanzi: "没", pinyin: "méi", vi: "Không có", example: "没有 (Không có)", category: "Lượng từ & Hư từ" },
    { id: 80, hanzi: "很", pinyin: "hěn", vi: "Rất", example: "很好 (Rất tốt)", category: "Lượng từ & Hư từ" }
];
